version: "3.9"
   
services:
  db:
    container_name: db
    image: postgres
    env_file:
      - .env
    volumes:
      - ./pgdata_dev/db:/var/lib/postgresql/data
  
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    env_file:
      - .env
    ports:
      - "5050:80"
    volumes:
      - ./pgdata_pgadmin:/root/.pgadmin
    depends_on:
      - db

  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
